service: crons
frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  timeout: 60
  region: ${opt:region, env:AWS_DEFAULT_REGION, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*
