export const ProcessingStages = {
  UPLOADED: "UPLOADED",
  EXTRACTING_CONTENT: "EXTRACTING_CONTENT",
  GENERATING_QUESTIONS: "GENERATING_QUESTIONS",
  SAVING_IN_DATABASE: "SAVING_IN_DATABASE",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
};

export const sourceType = {
    S3: "s3",
    YOUTUBE: "youtube"
}
